import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
// material
import {
  Card,
  CardContent,
  Stack,
  Typography,
  Grid,
  TextField,
  Box,
  Button,
  IconButton,
} from "@mui/material";
// components
import { Select } from "components";
import RootStyled from "./styled";
// utils
import ReactSvg from "utils/reactSVG";

const data = ["Physical", "Digital", "Physical"];
const types = ["Physical", "Digital"];

export default function EditProductForm() {
  const [state, setState] = useState(true);
  const navigate = useNavigate();
  return (
    <RootStyled>
      {[1, 2].map((v) => (
        <Card key={v} className="paper-card">
          <CardContent>
            <Grid container spacing={3}>
              <Grid item lg={4}>
                <Stack spacing={1}>
                  <Typography variant="body1" fontWeight={600}>
                    Tone
                  </Typography>
                  <Select data={data} label="Defult" />
                </Stack>
              </Grid>
              <Grid item lg={4}>
                <Stack spacing={1}>
                  <Typography variant="body1" fontWeight={600}>
                    Writing Style
                  </Typography>
                  <Select data={types} label="Defult" />
                </Stack>
              </Grid>
              <Grid item lg={12}>
                <Box position={"relative"}>
                  <TextField
                    multiline
                    className={`describe ${state && "active"}`}
                    rows={4}
                    fullWidth
                    autoComplete="describe"
                    type={"text"}
                    defaultValue="Text generated by  ouly (Ai)"
                    InputProps={{
                      readOnly: state,
                    }}
                  />
                  <Box className="editable-box">
                    <Stack>
                      <IconButton size="small" onClick={() => setState(false)}>
                        <ReactSvg name="sparkles" width="9px" height={11} />
                      </IconButton>

                      <IconButton size="small">
                        <ReactSvg name="replace" width="9px" height={11} />
                      </IconButton>
                    </Stack>
                  </Box>
                </Box>
              </Grid>
            </Grid>
          </CardContent>
        </Card>
      ))}
      <Box className="width-box" ml="auto">
        <Stack spacing={3} direction="row">
          <Button variant="outlined" size="large" color="secondary" fullWidth>
            Back
          </Button>
          <Button
            variant="contained"
            size="large"
            color="primary"
            onClick={() => navigate("/dashboard/advantages-product")}
            fullWidth
          >
            continue
          </Button>
        </Stack>
      </Box>
    </RootStyled>
  );
}
