import React from "react";
import { useNavigate } from "react-router-dom";
// material
import {
  Card,
  CardContent,
  Stack,
  Typography,
  Grid,
  TextField,
  Box,
  Button,
} from "@mui/material";
// components
import { Select } from "components";
import RootStyled from "./styled";

const data = ["Physical", "Digital", "Physical"];
const types = ["Physical", "Digital"];

export default function EditProductForm() {
  const navigate = useNavigate();
  return (
    <RootStyled>
      {[1, 2].map((v) => (
        <Card key={v} className="paper-card">
          <CardContent>
            <Grid container spacing={3}>
              <Grid item lg={4}>
                <Stack spacing={1}>
                  <Typography variant="body1" fontWeight={600}>
                    Tone
                  </Typography>
                  <Select data={data} label="Defult" />
                </Stack>
              </Grid>
              <Grid item lg={4}>
                <Stack spacing={1}>
                  <Typography variant="body1" fontWeight={600}>
                    Writing Style
                  </Typography>
                  <Select data={types} label="Defult" />
                </Stack>
              </Grid>
              <Grid item lg={12}>
                <TextField
                  multiline
                  className="describe"
                  rows={4}
                  fullWidth
                  autoComplete="describe"
                  type={"text"}
                  placeholder="Text generated by  ouly (Ai)"
                />
              </Grid>
            </Grid>
          </CardContent>
        </Card>
      ))}
      <Box className="width-box" ml="auto">
        <Stack spacing={3} direction="row">
          <Button variant="outlined" size="large" color="secondary" fullWidth>
            Back
          </Button>
          <Button
            variant="contained"
            size="large"
            color="primary"
            onClick={() => navigate("/dashboard/advantages-product")}
            fullWidth
          >
            continue
          </Button>
        </Stack>
      </Box>
    </RootStyled>
  );
}
